language: ruby

install: gem install jekyll  html-proofer 

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

script: jekyll build -s src -d ./site  && htmlproofer ./site

deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
  script: ./deploy.sh
  

  

sudo: false
